name: Bump SemVer Tags

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize, ready_for_review]

jobs:
  check-pr:
    uses: ./.github/workflows/shared-bump-semver-tags.yaml