name: Bump SemVer Tags

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/*'

jobs:
  check-pr:
    uses: ./.github/workflows/shared-bump-semver-tags.yaml
    secret:
      PUBLISH_PAT: ${{ secrets.GITHUB_TOKEN }}