name: Validate release info

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize, ready_for_review]
    paths:
      - '.github/workflows/*'

jobs:
  check-pr:
    uses: ./.github/workflows/shared-validate-semver-tags.yaml