name: Create Release
on:
  workflow_call:
    inputs:
      build-command:
        description: The command to use when building the package
        required: true
        type: string
      files:
        description: Files to publish with the release
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup go
        uses: actions/setup-go@v6
        with:
          go-version: '^1.24.6'
      - name: Make
        run: ${{ inputs.build-command }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ inputs.files }}
